### PR TITLE
Add assert.noObjectContent() and assert.noJsonFileContent()

### LINKED ISSUE #15: assert.noObjectContent and assert.noJsonFileContent methods
As we have assert.noFileContent(), wouldn't be useful also to have assert.noObjectContent and assert.noJsonFileContent ?

### PR DESCRIPTION
**Pull request by fernandopasik**
Fix #15

### CODE REVIEW

**Comment by SBoudrias** [comment]
This is great!

Would you mind adding them to the readme documentation?

**Comment by fernandopasik** [comment]
Yes of course! Added to README.md

**Comment by SBoudrias** [comment]
Thanks a ton!

**Comment by fernandopasik** [comment]
@SBoudrias thanks for your support!

**Pull request merged**
